version: "3.8"
services:
  payment-reminder-service:
    image: payment-reminder-service:latest
    depends_on:
      - zookeeper
      - kafka
    environment:
      ENVIRONMENT: DEV
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "payment-events-dev:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
