paymentReminder:
    eventSource:
        kafka:
            clients:
                security:
                    protocol: PLAINTEXT
                timeoutInSeconds: 300
                bootstrapServers: 
                    - kafka:9092
            consumers:
                paymentEvents:
                    consumerGroup: payment-reminder
                    topic: payment-events-dev
